export const QUESTIONS = [
 "What is the full legal name of the company?",
    "When was Cubosquare Technology founded?",
    "What is the legal structure of Cubosquare Technology?",
    "What is the vision of Cubosquare Technology?",
    "What is the mission of Cubosquare Technology?",
    "What are the core values of Cubosquare?",
    "What are the key milestones in Cubosquare's history?",
    "How did Cubosquare evolve from a proprietorship to a Private Limited company?",
    "What is Cubosquare's approach to digital transformation?",
    "What makes Cubosquare different from other technology companies?",
    "What services does Cubosquare offer?",
    "What web development services does Cubosquare provide?",
    "Which front-end technologies does Cubosquare use for web development?",
    "Which back-end technologies does Cubosquare use?",
    "What CMS platforms does Cubosquare work with?",
    "Does Cubosquare develop mobile applications?",
    "What platforms does Cubosquare support for mobile app development?",
    "Does Cubosquare offer digital marketing services?",
    "What digital marketing services are available at Cubosquare?",
    "Does Cubosquare provide blockchain solutions?",
    "What blockchain services does Cubosquare offer?",
    "Does Cubosquare develop IoT applications?",
    "What IoT applications does Cubosquare create?",
    "Does Cubosquare offer UI/UX design services?",
    "What UI/UX design services are available?",
    "Does Cubosquare handle research-based projects?",
    "What are the key differentiators of Cubosquare's services?",
    "What technologies does Cubosquare use for front-end development?",
    "Which JavaScript frameworks does Cubosquare work with?",
    "What back-end technologies does Cubosquare specialize in?",
    "Which databases does Cubosquare use?",
    "Does Cubosquare use relational or non-relational databases?",
    "What mobile development technologies does Cubosquare use?",
    "Does Cubosquare develop native or cross-platform mobile apps?",
    "Which cloud platforms does Cubosquare work with?",
    "What DevOps tools does Cubosquare use?",
    "Does Cubosquare work with AI and machine learning?",
    "What AI applications does Cubosquare develop?",
    "Does Cubosquare work with blockchain technology?",
    "What IoT technologies does Cubosquare use?",
    "Which UI/UX design tools does Cubosquare use?",
    "What testing tools does Cubosquare employ?",
    "What makes Cubosquare's technology stack adaptable?",
    "Which industries does Cubosquare serve?",
    "Does Cubosquare work with e-commerce businesses?",
    "What e-commerce solutions does Cubosquare provide?",
    "Does Cubosquare have healthcare industry experience?",
    "What healthcare solutions does Cubosquare offer?",
    "Does Cubosquare work with educational institutions?",
    "What education technology solutions does Cubosquare provide?",
    "Does Cubosquare serve the finance sector?",
    "What financial technology solutions does Cubosquare offer?",
    "Does Cubosquare work with retail businesses?",
    "What retail solutions does Cubosquare provide?",
    "Does Cubosquare have logistics and supply chain expertise?",
    "What logistics solutions does Cubosquare offer?",
    "Can you provide examples of Cubosquare's successful projects?",
    "What is the Software Development Life Cycle (SDLC)?",
    "What are the key phases of SDLC at Cubosquare?",
    "What happens during the requirement analysis phase?",
    "What is involved in the system design phase?",
    "What occurs during the development phase?",
    "How does Cubosquare handle testing?",
    "What is the deployment process at Cubosquare?",
    "How does Cubosquare handle maintenance and updates?",
    "What is the Waterfall Model?",
    "When is the Waterfall Model most suitable?",
    "What are the advantages of the Waterfall Model?",
    "What are the disadvantages of the Waterfall Model?",
    "What is the RAD (Rapid Application Development) Model?",
    "When is the RAD Model most suitable?",
    "What are the advantages of the RAD Model?",
    "What are the disadvantages of the RAD Model?",
    "What is the Spiral Model?",
    "When is the Spiral Model most suitable?",
    "What are the advantages of the Spiral Model?",
    "What are the disadvantages of the Spiral Model?",
    "How does Cubosquare choose the right development model?",
    "What partnership models does Cubosquare offer?",
    "What is the Fixed Bid Model?",
    "When is the Fixed Bid Model most suitable?",
    "What are the advantages of the Fixed Bid Model?",
    "What are the disadvantages of the Fixed Bid Model?",
    "What is the Retainer Model?",
    "When is the Retainer Model most suitable?",
    "What are the advantages of the Retainer Model?",
    "What are the disadvantages of the Retainer Model?",
    "What is the Time and Material Model?",
    "When is the Time and Material Model most suitable?",
    "What are the advantages of the Time and Material Model?",
    "What are the disadvantages of the Time and Material Model?",
    "What is the Dedicated Resource Model?",
    "When is the Dedicated Resource Model most suitable?",
    "What are the advantages of the Dedicated Resource Model?",
    "What are the disadvantages of the Dedicated Resource Model?",
    "What is the Joint Venture and Co-Development Model?",
    "When is the Joint Venture Model most suitable?",
    "What are the advantages of the Joint Venture Model?",
    "What are the disadvantages of the Joint Venture Model?",
    "What is a Strategic Technology Partnership?",
    "When is a Strategic Technology Partnership suitable?",
    "What are the advantages of Strategic Technology Partnerships?",
    "What are the disadvantages of Strategic Technology Partnerships?",
    "What is the White Label Model?",
    "When is the White Label Model most suitable?",
    "What are the advantages of the White Label Model?",
    "What are the disadvantages of the White Label Model?",
    "What are Cubosquare's key achievements?",
    "Has Cubosquare delivered successful e-commerce projects?",
    "Has Cubosquare worked on healthcare projects?",
    "Has Cubosquare developed educational platforms?",
    "Has Cubosquare created finance applications?",
    "What is the impact of Cubosquare's e-commerce platform project?",
    "What is the impact of Cubosquare's telemedicine platform?",
    "What is the impact of Cubosquare's learning management system?",
    "What is the impact of Cubosquare's mobile banking app?",
    "Has Cubosquare expanded globally?",
    "Which regions does Cubosquare serve?",
    "Does Cubosquare adopt emerging technologies?",
    "What do clients say about Cubosquare?",
    "Has Cubosquare received any industry awards?",
    "Who are Cubosquare's notable partners?",
    "Does Cubosquare invest in Research and Development?",
    "How does Cubosquare ensure continuous learning?",
    "What are Cubosquare's future goals?",
    "Is Cubosquare planning to expand globally?",
    "Which new markets is Cubosquare targeting?",
    "Is Cubosquare developing AI-based products?",
    "What is Cubosquare's AI call mimicking technology?",
    "What are the features of Cubosquare's AI call mimicking system?",
    "What is Cubosquare's AI chatbot product?",
    "What are the features of Cubosquare's AI chatbot?",
    "Does Cubosquare offer cloud computing solutions?",
    "Is Cubosquare focusing on sustainability?",
    "What green technologies does Cubosquare promote?",
    "How is Cubosquare enhancing customer experience?",
    "Is Cubosquare expanding its talent pool?",
    "Is Cubosquare developing proprietary products?",
    "What is Cubosquare's approach to cybersecurity?",
    "How does Cubosquare handle data security?",
    "How can I contact Cubosquare?",
    "What is Cubosquare's email address for support?",
    "What is Cubosquare's phone number?",
    "Where is Cubosquare's Mumbai office located?",
    "Where is Cubosquare's Pune office located?",
    "Where is Cubosquare's Kanpur office located?",
    "Does Cubosquare have an office in Canada?",
    "Where is Cubosquare's Toronto office located?",
    "Does Cubosquare offer live chat support?",
    "Does Cubosquare have a client portal?",
    "What is the emergency support helpline number?",
    "Is emergency support available 24/7?",
    "Does Cubosquare assign dedicated project managers?",
    "How often does Cubosquare provide project updates?",
    "Does Cubosquare offer consultation meetings?",
    "What is included in Cubosquare's client success program?",
    "Does Cubosquare provide onboarding assistance?",
    "Does Cubosquare offer continuous improvement services?",
    "How does Cubosquare collect client feedback?",
    "How can I request a demo from Cubosquare?",
    "How can I explore Cubosquare's portfolio?",
    "Can I partner with Cubosquare?",
    "How can I join Cubosquare's partner network?",
    "How can I stay updated with Cubosquare's latest news?",
    "What is Cubosquare's approach to customer-centricity?",
    "Does Cubosquare provide end-to-end support?",
    "What was the outcome of the healthcare remote monitoring app?",
    "What was the impact of the e-commerce platform for the retail chain?",
    "What was the result of the IoT-enabled smart home solutions project?",
    "How much did hospital visits reduce with Cubosquare's telemedicine platform?",
    "How much did sales increase with the e-commerce platform?",
    "How many educational institutions use Cubosquare's LMS?",
    "What was the improvement in mobile transaction volumes for the banking app?",
    "Does Cubosquare use HTML5?",
    "Does Cubosquare use CSS3?",
    "Does Cubosquare use ReactJS?",
    "Does Cubosquare use AngularJS?",
    "Does Cubosquare use Vue.js?",
    "Does Cubosquare use Node.js?",
    "Does Cubosquare use Python?",
    "Does Cubosquare use PHP?",
    "Does Cubosquare use Laravel?",
    "Does Cubosquare use MySQL?",
    "Does Cubosquare use PostgreSQL?",
    "Does Cubosquare use MongoDB?",
    "Does Cubosquare use Firebase?",
    "Does Cubosquare use Flutter?",
    "Does Cubosquare use React Native?",
    "Does Cubosquare use Swift?",
    "Does Cubosquare use Kotlin?",
    "Does Cubosquare use AWS?",
    "Does Cubosquare use Google Cloud Platform?",
    "Does Cubosquare use Microsoft Azure?",
    "Does Cubosquare use Docker?",
    "Does Cubosquare use Kubernetes?",
    "Does Cubosquare use Jenkins?",
    "Does Cubosquare use Selenium?",
    "Does Cubosquare use Appium?",
    "Does Cubosquare use Apache JMeter?",
    "Does Cubosquare use Figma?",
    "Does Cubosquare use Adobe XD?",
    "Does Cubosquare use Sketch?",
    "Does Cubosquare use InVision?",
    "Does Cubosquare use WordPress?",
    "Does Cubosquare use Drupal?",
    "Does Cubosquare use Magento?",
    "Does Cubosquare offer custom website development?",
    "Does Cubosquare build e-commerce solutions?",
    "Does Cubosquare develop enterprise web applications?",
    "Does Cubosquare provide website maintenance?",
    "Does Cubosquare offer app design and prototyping?",
    "Does Cubosquare handle app deployment?",
    "Does Cubosquare integrate APIs with mobile apps?",
    "Does Cubosquare offer SEO services?",
    "Does Cubosquare provide social media marketing?",
    "Does Cubosquare run PPC campaigns?",
    "Does Cubosquare offer content marketing?",
    "Does Cubosquare develop smart contracts?",
    "Does Cubosquare create decentralized applications?",
    "Does Cubosquare offer blockchain consulting?",
    "Does Cubosquare develop home automation solutions?",
    "Does Cubosquare create smart city solutions?",
    "Does Cubosquare work on Industrial IoT?",
    "Does Cubosquare offer wireframing services?",
    "Does Cubosquare conduct user research?",
    "Does Cubosquare create interactive designs?",
    "Why should I choose Cubosquare over competitors?",
    "What is Cubosquare's competitive advantage?",
    "How does Cubosquare ensure quality?",
    "How does Cubosquare handle project complexity?",
    "What is Cubosquare's approach to innovation?",
    "How does Cubosquare prioritize client needs?",
    "Does Cubosquare offer customizable partnership models?",
    "What is Cubosquare's proven track record?",
    "How does Cubosquare maintain long-term client relationships?",
    "Is Cubosquare investing in AI research?",
    "Is Cubosquare developing blockchain innovations?",
    "Is Cubosquare working on IoT platforms?",
    "What are Cubosquare's plans for cloud expansion?",
    "How is Cubosquare addressing cybersecurity challenges?",
    "What is Cubosquare's strategy for talent development?",
    "Is Cubosquare developing SaaS products?",
    "Is Cubosquare planning to launch white-label solutions?",
    "Has Cubosquare partnered with AWS?",
    "Has Cubosquare partnered with Google Cloud?",
    "Has Cubosquare collaborated with digital marketing firms?",
    "Does Cubosquare participate in technology forums?",
    "Does Cubosquare attend global conferences?",
    "What is Cubosquare's approach to requirement analysis?",
    "How does Cubosquare handle system design?",
    "What is Cubosquare's development methodology?",
    "How does Cubosquare ensure software quality through testing?",
    "What is Cubosquare's deployment strategy?",
    "How does Cubosquare manage software maintenance?",
    "What impact has Cubosquare made in the e-commerce industry?",
    "What impact has Cubosquare made in healthcare?",
    "What impact has Cubosquare made in education?",
    "What impact has Cubosquare made in finance?",
    "What impact has Cubosquare made in retail?",
    "What impact has Cubosquare made in logistics?",
    "What are the benefits of partnering with Cubosquare?",
    "How does Cubosquare support white-label partnerships?",
    "What expertise does Cubosquare bring to partnerships?",
    "How does Cubosquare ensure long-term partnership success?",
    "What AI products is Cubosquare launching?",
    "Can Cubosquare's AI chatbot be integrated with CRM systems?",
    "Does Cubosquare's AI chatbot support multiple languages?",
    "Can Cubosquare's call mimicking system handle sales calls?",
    "Can Cubosquare's call mimicking system handle support calls?",
    "Is Cubosquare's AI chatbot available 24/7?",
    "Does Cubosquare's AI chatbot learn from interactions?",
    "What is Cubosquare's approach to innovation?",
    "What is Cubosquare's approach to integrity?",
    "What is Cubosquare's approach to collaboration?",
    "What is Cubosquare's approach to customer-centricity?",
    "What is Cubosquare's approach to excellence?"
];
